### ISSUE TITLE
Unable to import project into Studio

### ISSUE THREAD

**Issue by kosso** [hansemannn/titanium-bluetooth#15]
Hi,
I've forked this and tried to import the project into Studio and it does not seem to recognise the iOS version. Only Package Android Module is available. 

I seem to often have this problem with cross-platform (dual) modules. And I have never been able to set one up myself. (Always two separate projects).

Is there a trick I'm missing? ;)  Thanks.

**Comment by hansemannn** [comment]
Probably Studio only detects "iphone" directories in there, not "ios". No idea...

**Comment by kosso** [comment]
Hmm. But how did you create the dual-platform module?  There is no option in Studio to create both at once, since it is a 'radio' option. And trying to create one after another causes Studio to complain too.

**Comment by kosso** [comment]
btw. Great work. Very comprehensive. ;)

**Comment by kosso** [comment]
btw # 2 : I noticed that the startAdvertising and stopAdvertising methods are not documented.  Are they working?  

(I built a small "advertising-only" module last night : https://github.com/kosso/tibeacon )

**Comment by hansemannn** [comment]
Saw it, would be great to have one module to rule them all. Should work though. I never created or built through Studio. Please feel free to help maintaining!

**Comment by kosso** [comment]
I think it may be time for a Jira ticket... ;) 

:+1:

**Comment by hansemannn** [comment]
Works for me when renaming to "iphone".
<img width="344" alt="bildschirmfoto 2017-03-29 um 13 14 17" src="https://cloud.githubusercontent.com/assets/10667698/24452040/ab1ab984-1481-11e7-8b25-592f304c5c34.png">

**Comment by hansemannn** [comment]
Fixed in https://github.com/hansemannn/titanium-bluetooth/commit/0dcf755618502dd81a846d905512ab18e47c79a8.

**Comment by kosso** [comment]
:+1:
