### ISSUE TITLE
Not a issue but a question

### ISSUE THREAD

**Issue by PietroGranati** [hansemannn/titanium-bluetooth#16]
Maybe is my fault, but how I can connect to a BLE device once I found that?

**Comment by yoannwyffels** [comment]
Hello,

I'm having same question :)
Do you have any answer ?

Thanks !

**Comment by hansemannn** [comment]
Please check one of the available [`CoreBluetooth tutorials`](https://www.raywenderlich.com/52080/introduction-core-bluetooth-building-heart-rate-monitor) tutorials for more infos.
