### ISSUE TITLE
discoverCharacteristicsForService(..) => Index 1 beyond bounds

### ISSUE THREAD

**Issue by yoannwyffels** [hansemannn/titanium-bluetooth#17]
Hello,

I'm trying to accomplish connection and discover Bluetooth services.
It's working:

!!!! Found MLT !!!!!
[INFO] :   didConnectPeripheral
[INFO] :   {
[INFO] :       bubbles = 1;
[INFO] :       cancelBubble = 0;
[INFO] :       peripheral = "[object TiBluetoothPeripheral]";
[INFO] :       source = "[object TiBluetoothCentralManager]";
[INFO] :       type = didConnectPeripheral;
[INFO] :   }
[INFO] :   State: 2
[INFO] :   RSSI: 0
[INFO] :   Name: MLT-BT05
[INFO] :   didDiscoverServices
[INFO] :   {
[INFO] :       bubbles = 1;
[INFO] :       cancelBubble = 0;
[INFO] :       error = "<null>";
[INFO] :       peripheral = "[object TiBluetoothPeripheral]";
[INFO] :       source = "[object TiBluetoothPeripheral]";
[INFO] :       type = didDiscoverServices;
[INFO] :   }

Now, I'm in "myPeripheral.addEventListener('didDiscoverServices') event, and trying to get characteristics for service by running this code:

myPeripheral.discoverCharacteristicsForService(myPeripheral.services[0]);

But error:
message = "*** -[__NSArrayM objectAtIndex:]: index 1 beyond bounds [0 .. 0]";

I analysed source code and found there is a deprecated method "discoverCharacteristicsForService" with 2 arguments. This one running, but not firing any callback event.

What am I missing ?

**Comment by hansemannn** [comment]
Thanks, will check! Can you output the content of the `myPeripheral.services` array?

**Comment by hansemannn** [comment]
I checked the source. The correct usage is:
```js
myPeripheral.discoverCharacteristicsForService({
  service: myPeripheral.services[0],

  // Optional: Pass characteristics, remove when unused
  characteristics: null
});
```
