### ISSUE TITLE
Android build failed

### ISSUE THREAD

**Issue by bahinapster** [hansemannn/titanium-bluetooth#18]
Hello ,

i am trying to build the module for android but i am facing an issue with javac source and target as i think.
Titanium SDK 6.0.4
JDK 1.7

can you please help with this ?

`Failed to compile Java source files:
[ERROR] :  
[ERROR] :  warning: [options] bootstrap class path not set in conjunction with -source 1.6
[ERROR] :  Note: [KrollBindingGen] Running Kroll binding generator.
[ERROR] :  Note: [KrollBindingGen] No binding data found, creating new data file: org.appcelerator.titanium.bindings/ti.bluetooth.json
[ERROR] :  Note: [KrollBindingGen] Found binding for proxy TiBluetoothDevice
[ERROR] :  Note: [KrollBindingGen] Found binding for module TiBluetooth
[ERROR] :  Note: [KrollBindingGen] Generating JSON: file:/Users/*/Documents/Appcelerator_Studio_Workspace/titanium-bluetooth/android/build/generated/json/org/appcelerator/titanium/bindings/ti.bluetooth.json
[ERROR] :  /Users/*/Documents/Appcelerator_Studio_Workspace/titanium-bluetooth/android/src/ti/bluetooth/TiBluetoothDeviceProxy.java:33: error: cannot find symbol
[ERROR] :  		btDevice.connectGatt(ctx, autoConnect, new BluetoothGattCallbackHandler(this));
[ERROR] :  		                                           ^
[ERROR] :    symbol:   class BluetoothGattCallbackHandler
[ERROR] :    location: class TiBluetoothDeviceProxy
[ERROR] :  Note: /Users/*/Documents/Appcelerator_Studio_Workspace/titanium-bluetooth/android/src/ti/bluetooth/TiBluetoothGattCallbackHandler.java uses unchecked or unsafe operations.
[ERROR] :  Note: Recompile with -Xlint:unchecked for details.
[ERROR] :  1 error
[ERROR] :  1 warning`

**Comment by m1ga** [comment]
Sorry, there was a typo. Fixed now
