### ISSUE TITLE
Invalid method (createCentralManager) passed to TiBluetoothModule

### ISSUE THREAD

**Issue by bahinapster** [hansemannn/titanium-bluetooth#19]
Hello ,
i did a sample usage of the module , but it craches at launching when i call createCentralManager method.
SDK 6.0.4
IOS : 10.3.1

module version 1.0.3 beta ios

Attempted to load TiBluetoothCentralManagerProxy: Could not find class definition.
[ERROR] :  Script Error {
[ERROR] :      column = 203;
[ERROR] :      line = 1;
[ERROR] :      message = "invalid method (createCentralManager) passed to TiBluetoothModule";
[ERROR] :  }

**Comment by hansemannn** [comment]
Please build from the source, there has been 70 commits since the last beta version.

**Comment by hansemannn** [comment]
Keeping it open for now, let me draft a new beta version.

**Comment by hansemannn** [comment]
Drafted https://github.com/hansemannn/titanium-bluetooth/releases/tag/ios-1.0.0-beta.4

**Comment by bahinapster** [comment]
Hello hansemannn,

thank you for your replay, even from source or with the last commit i still have the same issue (beta4 included)

Best regards.
