### ISSUE TITLE
Documentation missing

### ISSUE THREAD

**Issue by focussing** [hansemannn/titanium-bluetooth#20]
Hi!

Until now I worked with the modules from Logicallabs. I would like to test the ti.bluetooth module in my apps. Could you complete or provide otherwise documentation, for example how to connect to a device, subscribe to characteristics, write to a characteristic, etc?

**Comment by hansemannn** [comment]
This project is community-based on lives from the contributions we and others make. An API documentation can be found in the [Wiki page](https://github.com/hansemannn/titanium-bluetooth/wiki) of this project, please feel free to add more to it.

**Comment by focussing** [comment]
Sorry, I was not aware of the wiki page.
That will help!
Thank you.
