### ISSUE TITLE
problem android module

### ISSUE THREAD

**Issue by rokko84** [hansemannn/titanium-bluetooth#26]
Hello,
I tried to create the module for android but i have this error:
Launching build and packaging failed
Build failed. Unable to locate generated zip file at /Users/rocco/Documents/Appcelerator_Studio_Workspace/hansemannn.ti.bluetooth-master/dist/ti.bluetooth-android-1.0.1.zip

Can you provide the zip file of the android module?

**Comment by hansemannn** [comment]
All releases are in the `Releases` tab.
