### ISSUE TITLE
Android crash

### ISSUE THREAD

**Issue by bahinapster** [hansemannn/titanium-bluetooth#30]
Hello,

I have installed ti.module for android, but unfortunately the applications crashes  directly when i include the module.

SDK : 6.3.0 GA
Android : 4.4

Best regards.

**Comment by michelelazzarato** [comment]
Hi,
I'm try to use ti.bluetooth with android device with your sample code in app.js but when I click button start scan my device don't appear il info list.
Is this module for android complete?
Thanks in advance,

    Michele.

**Comment by hansemannn** [comment]
Missing test case, closing for now.
