### ISSUE TITLE
BLE Android don't work fine

### ISSUE THREAD

**Issue by lazzaratom** [hansemannn/titanium-bluetooth#39]
Hi aca-mobile,
I have tried to implement code for android device with new version of this library. didDiscoverPeripheral find my peripheral (in my sample UART Service);
didConnectPeripheral run correctly;
didUpdateValueForCharacteristic don't run correctly:

This is my log:

[INFO] : didDiscoverPeripheral
[INFO] : UART Service
[INFO] : Connect to [object TiBluetoothPeripheral]
[INFO] : e.peripheral: [object TiBluetoothPeripheral]
[INFO] : e.peripheral.name: UART Service
[INFO] : connecting
[INFO] : Connected to Periperal...
[INFO] : Service Discovery...
[INFO] : peripheral has 3 service(s)
[INFO] : service: 00001801-0000-1000-8000-00805F9B34FB
[INFO] : service: 00001800-0000-1000-8000-00805F9B34FB
[INFO] : service: 6E400001-B5A3-F393-E0A9-E50E24DCCA9E
[INFO] : service Found: 6E400001-B5A3-F393-E0A9-E50E24DCCA9E
[INFO] : Service Found: 00001801-0000-1000-8000-00805F9B34FB
[INFO] : Service Found: 00001800-0000-1000-8000-00805F9B34FB
[INFO] : Service Found: 6E400001-B5A3-F393-E0A9-E50E24DCCA9E
[INFO] : Immediate Alert Service Found6E400001-B5A3-F393-E0A9-E50E24DCCA9E
[INFO] : Characteristic ID: 6E400003-B5A3-F393-E0A9-E50E24DCCA9E
[INFO] : Alert Level Characteristic Found
[INFO] : 6E400003-B5A3-F393-E0A9-E50E24DCCA9E
[INFO] : didUpdateValueForCharacteristic passed -->6E400003-B5A3-F393-E0A9-E50E24DCCA9E
[INFO] : Characteristic ID: 6E400002-B5A3-F393-E0A9-E50E24DCCA9E
[INFO] : Characteristic ID: 6E400003-B5A3-F393-E0A9-E50E24DCCA9E
[INFO] : Alert Level Characteristic Found
[INFO] : 6E400003-B5A3-F393-E0A9-E50E24DCCA9E
[INFO] : didUpdateValueForCharacteristic passed -->6E400003-B5A3-F393-E0A9-E50E24DCCA9E
[INFO] : Characteristic ID: 6E400002-B5A3-F393-E0A9-E50E24DCCA9E

And this is my sample code:

var BLE = require('ti.bluetooth');
var centralManager = BLE.createCentralManager();
var value = '';
var connectedPeripheral;

var SERVICE_UUID = '6E400001-B5A3-F393-E0A9-E50E24DCCA9E';
var CHARACTERISTIC_UUID_RX = '6E400002-B5A3-F393-E0A9-E50E24DCCA9E';
var CHARACTERISTIC_UUID_TX = '6E400003-B5A3-F393-E0A9-E50E24DCCA9E';

var win = Ti.UI.createWindow({
backgroundColor : '#fff'
});

var btn1 = Ti.UI.createButton({
title : 'Start scan',
top : 40
});

btn1.addEventListener('click', function() {
if (centralManager.isScanning()) {
alert('Already scanning, please stop scan first!');
return;
} else if (centralManager.getState() != BLE.MANAGER_STATE_POWERED_ON) {
alert('The BLE manager needs to be powered on before. Call initialize().');
return;
}

```
centralManager.startScan();
```
});

var btn2 = Ti.UI.createButton({
title : 'Stop scan',
top : 100
});

btn2.addEventListener('click', function() {
if (!centralManager.isScanning()) {
alert('Not scanning!');
return;
}
centralManager.stopScan();
});

/**

* Central Manager Events
  */

centralManager.addEventListener('didDiscoverPeripheral', function(e) {
Ti.API.info('didDiscoverPeripheral');
Ti.API.info(e.peripheral.name);

```
Ti.API.info('Connect to ' + e.peripheral);

if (e.peripheral.name == 'UART Service') {
	Ti.API.info('e.peripheral:', e.peripheral);
	Ti.API.info('e.peripheral.name:', e.peripheral.name);
	Ti.API.info('connecting');

	centralManager.stopScan();
	centralManager.connectPeripheral(e.peripheral, {
		notifyOnConnection : true,
		notifyOnDisconnection : true
	});

}
```
});

centralManager.addEventListener('didUpdateState', function(e) {
Ti.API.info('didUpdateState');

```
switch (e.state) {
case BLE.MANAGER_STATE_RESETTING:
	Ti.API.info('Resetting');
	break;

case BLE.MANAGER_STATE_UNSUPPORTED:
	Ti.API.info('Unsupported');
	break;

case BLE.MANAGER_STATE_UNAUTHORIZED:
	Ti.API.info('Unauthorized');
	break;

case BLE.MANAGER_STATE_POWERED_OFF:
	Ti.API.info('Powered Off');
	break;

case BLE.MANAGER_STATE_POWERED_ON:
	Ti.API.info('Powered On');
	break;

case BLE.MANAGER_STATE_UNKNOWN:
default:
	Ti.API.info('Unknown');
	break;
}
```
});

centralManager.addEventListener('didConnectPeripheral', function(e) {
Ti.API.info('Connected to Periperal...');

```
connectedPeripheral = e.peripheral;

connectedPeripheral.addEventListener('didDiscoverServices', function(e) {
	Ti.API.info('Service Discovery...');

	p = e.peripheral;
	Ti.API.info('peripheral has', p.services.length, 'service(s)');

	p.services.forEach(function(service) {
		// Assign service
		Ti.API.info("service: " + service.uuid);
		if (service.uuid == SERVICE_UUID) {
			Ti.API.info("service Found: " + service.uuid);
			p.addEventListener('didDiscoverCharacteristicsForService', function(e) {
				var peripheral = e.peripheral;
				var characteristics = e.service.characteristics;

				characteristics.forEach(function(characteristic) {
					Ti.API.info('Characteristic ID:', characteristic.uuid);

					if (characteristic.uuid == CHARACTERISTIC_UUID_TX) {
						Ti.API.info('Alert Level Characteristic Found');
						Ti.API.info(characteristic.uuid);

						peripheral.addEventListener('didUpdateValueForCharacteristic', _didUpdateValueForCharacteristic);
						peripheral.setNotifyValueForCharacteristic(true, characteristic);
						Ti.API.info('didUpdateValueForCharacteristic passed -->' + characteristic.uuid);

						function _didUpdateValueForCharacteristic(e) {
							var characteristic = e.characteristic.value.toString().replace(/(\r\n|\n|\r)/gm, "");
							value = value + characteristic;
							Ti.API.info(' data:' + characteristic + ' length:' + characteristic.length);
						}

					}
				});
			});

			p.services.forEach(function(service) {
				Ti.API.info("Service Found: " + service.uuid);

				if (service.uuid == SERVICE_UUID) {
					Ti.API.info('Immediate Alert Service Found' + service.uuid);
					p.discoverCharacteristicsForService({
						characteristics : [],
						service : service
					});
				}
			});
			p.discoverCharacteristicsForService({
				characteristics : [],
				service : service
			});
		}
	});
});

// Discover services
connectedPeripheral.discoverServices();
```
});

centralManager.addEventListener('didDisconnectPeripheral', function(e) {
Ti.API.info('didDisconnectPeripheral');
Ti.API.info(e);
});

centralManager.addEventListener('willRestoreState', function(e) {
Ti.API.info('willRestoreState');
Ti.API.info(e);
});

centralManager.addEventListener('didFailToConnectPeripheral', function(e) {
Ti.API.info('didFailToConnectPeripheral');
Ti.API.info(e);
});

/**

* Peripheral Manager Events
  */

if (Ti.Platform.name === 'iPhone OS') {
peripheralManager.addEventListener('didUpdateState', function(e) {
Ti.API.info('didUpdateState');
Ti.API.info(e);
});

```
peripheralManager.addEventListener('willRestoreState', function(e) {
	Ti.API.info('willRestoreState');
	Ti.API.info(e);
});

peripheralManager.addEventListener('didStartAdvertising', function(e) {
	Ti.API.info('didStartAdvertising');
	Ti.API.info(e);
});

peripheralManager.addEventListener('didAddService', function(e) {
	Ti.API.info('didAddService');
	Ti.API.info(e);
});

peripheralManager.addEventListener('didSubscribeToCharacteristic', function(e) {
	Ti.API.info('didSubscribeToCharacteristic');
	Ti.API.info(e);
});

peripheralManager.addEventListener('didUnsubscribeFromCharacteristic', function(e) {
	Ti.API.info('didUnsubscribeFromCharacteristic');
	Ti.API.info(e);
});

peripheralManager.addEventListener('didReceiveReadRequest', function(e) {
	Ti.API.info('didReceiveReadRequest');
	Ti.API.info(e);
});

peripheralManager.addEventListener('didReceiveWriteRequests', function(e) {
	Ti.API.info('didReceiveWriteRequests');
	Ti.API.info(e);
});

peripheralManager.addEventListener('readyToUpdateSubscribers', function(e) {
	Ti.API.info('readyToUpdateSubscribers');
	Ti.API.info(e);
});
```
}

win.add(btn1);
win.add(btn2);
win.open();

Whats's wrong in my code?
The same code in IOS work fine!

Best regards,
Michele.

**Comment by lazzaratom** [comment]
Hi to all,
   where can i find a complete example code to test module on android?
Now release 3.0.0 not work fine.
Can you help me?
Best regards,

   Michele.

**Comment by michelelazzarato** [comment]
Hi everyone,
 I wanted to know if this development to someone works correctly because in my case I can't receive notifications from the external device. I would also like to receive a negative response so at least I don't lose more time.
Thanks for your collaboration,
   Michele.

**Comment by michelelazzarato** [comment]
Hi everyone,
 I have solved!!!
Thanks a lot,
   Michele.

**Comment by AmarDCintas** [comment]
Hi Michele,
I am facing same issue, can you please tell me how you fixed it.

**Comment by AmarDCintas** [comment]
> Hi everyone,
> I have solved!!!
> Thanks a lot,
> Michele.

Hi Michele,
I am facing same issue, can you please tell me how you fixed it.

**Comment by tav3lla** [comment]
Hi, i have the same issue. 
Can you help me?

**Comment by vamsi909** [comment]
> Hi everyone,
> I have solved!!!
> Thanks a lot,
> Michele.

Hi Michele can you please share the fix for the above issue , I am also getting same issue and stuck for android .

**Comment by gavelez35** [comment]
@m1ga @hansemannn Hi, I've been trying to get this module to work on Android 9.0 but I've been unsuccessful? It is working fine for iOS and the data is flowing through as expected. However, on my Android device, when I try to read the value property of the characteristic I get the following error:

[INFO]  ">>> CALLED processTestAvailable: 00000000-0000-1000-8000-BBBD00000011"
[WARN]  TiBlob: (main) [78014,80793] getFile not supported for non-file blob types.
[INFO]  "Current characteristic: {\"value\":{\"height\":0,\"uprightHeight\":0,\"type\":2,\"mimeType\":\"application/octet-stream\",\"text\":\"\\n\",\"nativePath\":null,\"width\":0,\"length\":1,\"uprightWidth\":0,\"size\":1,\"file\":null,\"apiName\":\"Ti.Blob\",\"bubbleParent\":true},\"uuid\":\"00000000-0000-1000-8000-BBBD00000011\",\"apiName\":\"Ti.Proxy\",\"bubbleParent\":true}"
[ERROR] TiExceptionHandler: (main) [8,80801] /alloy/controllers/bluetoothMain.js:219
[ERROR] TiExceptionHandler: lg("Characteristic UUID 2: "+charTTEST.value),
[ERROR] TiExceptionHandler:                                        ^
**[ERROR] TiExceptionHandler: Error: Attempt to get length of null array**
[ERROR] TiExceptionHandler:     at TiBluetoothPeripheral.processTestAvailable (/alloy/controllers/bluetoothMain.js:219:40)
[ERROR] TiExceptionHandler:     at TiBluetoothPeripheral.value (ti:/events.js:50:21)
[ERROR] TiExceptionHandler:     at TiBluetoothPeripheral.value (ti:/events.js:102:19)
[ERROR] TiExceptionHandler:
[ERROR] TiExceptionHandler:     java.io.ByteArrayInputStream.<init>(ByteArrayInputStream.java:106)
[ERROR] TiExceptionHandler:     org.appcelerator.titanium.TiBlob.getInputStream(TiBlob.java:382)
[ERROR] TiExceptionHandler:     org.appcelerator.titanium.TiBlob.guessContentTypeFromStream(TiBlob.java:200)
[ERROR] TiExceptionHandler:     org.appcelerator.titanium.TiBlob.loadBitmapInfo(TiBlob.java:266)
[ERROR] TiExceptionHandler:     org.appcelerator.titanium.TiBlob.blobFromData(TiBlob.java:189)
[ERROR] TiExceptionHandler:     org.appcelerator.titanium.TiBlob.blobFromData(TiBlob.java:172)
[ERROR] TiExceptionHandler:     ti.bluetooth.gatt.TiBluetoothCharacteristicProxy.getValue(TiBluetoothCharacteristicProxy.java:31)
[ERROR] TiExceptionHandler:     org.appcelerator.kroll.runtime.v8.V8Object.nativeFireEvent(Native Method)
[ERROR] TiExceptionHandler:     org.appcelerator.kroll.runtime.v8.V8Object.fireEvent(V8Object.java:63)
[ERROR] TiExceptionHandler:     org.appcelerator.kroll.KrollProxy.doFireEvent(KrollProxy.java:977)
[WARN]  RenderThread: type=1400 audit(0.0:481): avc: denied { read } for name="u:object_r:vendor_hwui_prop:s0" dev="tmpfs" ino=13171 scontext=u:r:untrusted_app:s0:c119,c256,c512,c768 tcontext=u:object_r:vendor_hwui_prop:s0 tclass=file permissive=0
[ERROR] libc: Access denied finding property "ro.vendor.hwui.texture_cache_size"
[ERROR] V8Exception: Exception occurred at /alloy/controllers/bluetoothMain.js:219: Uncaught Error: Attempt to get length of null array
[WARN]  RenderThread: type=1400 audit(0.0:482): avc: denied { read } for name="u:object_r:vendor_hwui_prop:s0" dev="tmpfs" ino=13171 scontext=u:r:untrusted_app:s0:c119,c256,c512,c768 tcontext=u:object_r:vendor_hwui_prop:s0 tclass=file permissive=0
[ERROR] libc: Access denied finding property "ro.vendor.hwui.texture_cache_size"
[INFO]  OpenGLRenderer: queryNativeWindowStatus 0x760ed88010 query=0 dataspace=0


**Here is my code snippet for when I start discovering characteristic:**

connectedPeripheral.addEventListener('didDiscoverCharacteristicsForService', function(e) {
        var peripheral          = e.peripheral;
        var listCharacteristics = e.service.characteristics;
        
        //PROCESS EACH CHARACTERISTIC, FIND TESTAVAIL AND REGISTER UPDATE LISTENER
        listCharacteristics.forEach(function(characteristic){
            lg("Characteristic Found: " + characteristic.uuid);

            if(characteristic.uuid == UUID_SPIN_TOUCH_TESTAVAIL){
                lg('***** TEST AVAIL CHARACTERISTIC! *****');
                // lg('TEST AVAIL value: ' + characteristic.value);

                var processTestAvailable = function(e){
                    
                    lg('>>> CALLED processTestAvailable: ' + e.characteristic.uuid);
                    lg('Current characteristic: ' + JSON.stringify(e.characteristic));

                    if(Ti.Platform.osname == 'iphone' || Ti.Platform.osname == 'ipad'){
                        peripheral.readValueForCharacteristic(charTTEST); //GET TEST DATA
                    } 

                    lg('Characteristic UUID 2: ' + charTTEST.value);

                    // if(commonHub.isSet(charTTEST) && commonHub.isSet(charTTEST.value)){
                    //     testData = charTTEST.value.toArrayBuffer(); //convert Blob to Array Buffer
                    // } else {
                    //     lg('TEST DATA was not available... ...');
                    // }

                    if(commonHub.isSet(testData) && testData.byteLength > 0){
                        //INFORM DEVICE THAT THE TRANSACTION IS DONE...
                        // if(commonHub.isSet(charTESTACK) && testData.byteLength > 0){
                        //     lg('Writing 1 to ' + charTESTACK.uuid);
                        //     var buffer = Ti.createBuffer({ value : 1});
                        //     peripheral.writeValueForCharacteristicWithType(buffer.toBlob(), charTESTACK, BLE.CHARACTERISTIC_PROPERTY_WRITE_WITHOUT_RESPONSE);
                        // } else {
                        //     lg('TEST ACK was not set...', 'warning');
                        // }

                        processTestDataAndClose();
                    } else {
                        lg('Did not receive test data yet... waiting...');
                    }
                };

                peripheral.addEventListener('didUpdateValueForCharacteristic', processTestAvailable);

                peripheral.setNotifyValueForCharacteristic(true, characteristic); //listen for updates to the TESTAVAIL characteristics
            } //end of testavail found

            if(characteristic.uuid == UUID_SPIN_TOUCH_TTEST){
                lg('***** TTEST CHARACTERISTIC! *****');
                // lg('TTEST value: ' + characteristic.value);

                charTTEST = characteristic;

                peripheral.setNotifyValueForCharacteristic(true, characteristic); //listen for updates to the TESTAVAIL characteristics
            }

            if(characteristic.uuid == UUID_SPIN_TOUCH_TESTACK){
                lg('***** TESTACK CHARACTERISTIC! *****');
                // lg('TESTACK value: ' + characteristic.value);

                charTESTACK = characteristic;
            }
        });
        
    });

**Comment by m1ga** [comment]
@gavelez35 please don't link us in tickets. And then check your code. You set `charTTEST` in:
```
if (characteristic.uuid == UUID_SPIN_TOUCH_TTEST) {
			lg('***** TTEST CHARACTERISTIC! *****');
			charTTEST = characteristic;
			peripheral.setNotifyValueForCharacteristic(true, characteristic); //listen for updates to the TESTAVAIL characteristics
		}
```
in that if and try to read it in another if-case inside an event. Try the code people posted above and if you need help using the module please use ti-slack or stackoverflow, not the ticket here.

I'll close this issue here. If there is still an issue with the module on Android feel free to open a new issue.
BTW: I'm preparing an update at https://github.com/hansemannn/titanium-bluetooth/pull/46

**Comment by gavelez35** [comment]
@m1ga okay thank you, as mentioned the same code worked fine for iOS. That charTTEST variable should still be in scope, but I'll confirm. I think my scenario is slightly different. I have to first wait for write event on one characteristic, which then tells me to read another characteristic for the data from the peripheral. I'll check out those other communication methods you mentioned. Again, what is confusing is that the same code works perfectly fine for iOS.

**Comment by m1ga** [comment]
there error appears here: https://github.com/grazianogrespan/titanium-bluetooth/blob/master/android/src/ti/bluetooth/gatt/TiBluetoothCharacteristicProxy.java#L59

so it looks like that `characteristic` (or `characteristic.getValue()`) is null.
