### ISSUE TITLE
Android - Unable to instantiate receiver

### ISSUE THREAD

**Issue by Chris0714** [hansemannn/titanium-bluetooth#40]
Receiver test 1
<receiver android:exported="true" android:name="ti.bluetooth.broadcastReceiver.TiBluetoohBroadcastReceiver" android:enabled="true">

Error log
Unable to instantiate receiver ti.bluetooth.broadcastReceiver.TiBluetoohBroadcastReceiver: java.lang.InstantiationException: java.lang.Class<ti.bluetooth.broadcastReceiver.TiBluetoohBroadcastReceiver> has no zero argument constructor

This error happened when I switch on the Bluetooth while the app is running.

**Comment by Chris0714** [comment]
reference : https://stackoverflow.com/questions/43128653/intentservice-error-no-default-constructor

public TiBluetoohBroadcastReceiver() {
  super();
}

Add these code to TiBluetoohBroadcastReceiver.java solve my problem.

**Comment by hansemannn** [comment]
@Chris0714 Please fill a pull request so others can benefit from this issue as well. Also, if an update occurs, you don't need to re-patch it. Thanks!

**Comment by Chris0714** [comment]
OK sir.

**Comment by Chris0714** [comment]
@hansemannn what is the next step after clicking the "new pull request" button ? i never done this before. Sorry.

**Comment by Chris0714** [comment]
public final class TiBluetoohBroadcastReceiver

remove the final

public class TiBluetoohBroadcastReceiver

**Comment by m1ga** [comment]
@Chris0714 can you please test this PR: https://github.com/hansemannn/titanium-bluetooth/pull/41
Binary is here: https://github.com/hansemannn/titanium-bluetooth/blob/a625ad60097523786ed45f41fc18f472840352f2/android/dist/ti.bluetooth-android-3.0.1.zip
