### ISSUE TITLE
Build for 8.2.0.GA?

### ISSUE THREAD

**Issue by kosso** [hansemannn/titanium-bluetooth#43]
Hi, 
I can't seem to get this to build using Ti. SDK 8.2.0.GA.   (ios)

Are you able to?

**Comment by kosso** [comment]
The XCode project seem to be very out of date now. :/

**Comment by kosso** [comment]
Still having no luck getting XCode to build this. 

(I'm attempting to add the readRSSI callback to be able to repeatedly measure signal strength using https://developer.apple.com/documentation/corebluetooth/cbperipheraldelegate/1620304-peripheral)

**Comment by hansemannn** [comment]
The event is added now and built with SDK 9+
